=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for BancardPixServiceClient::ApplicationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ApplicationsApi' do
  before do
    # run before each test
    @api_instance = BancardPixServiceClient::ApplicationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationsApi' do
    it 'should create an instance of ApplicationsApi' do
      expect(@api_instance).to be_instance_of(BancardPixServiceClient::ApplicationsApi)
    end
  end

  # unit tests for create_application
  # Create application
  # @param [Hash] opts the optional parameters
  # @option opts [ApplicationCreateRequest] :application_create_request 
  # @return [ShowApplication]
  describe 'create_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_application
  # Delete application
  # @param id id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_applications
  # List applications
  # @param [Hash] opts the optional parameters
  # @return [ListApplications]
  describe 'list_applications test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_application
  # Show application
  # @param id id
  # @param [Hash] opts the optional parameters
  # @return [ShowApplication]
  describe 'show_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_application
  # Update application
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [ApplicationUpdateRequest] :application_update_request 
  # @return [ShowApplication]
  describe 'update_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
