=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for BancardPixServiceClient::PaymentHooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentHooksApi' do
  before do
    # run before each test
    @api_instance = BancardPixServiceClient::PaymentHooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentHooksApi' do
    it 'should create an instance of PaymentHooksApi' do
      expect(@api_instance).to be_instance_of(BancardPixServiceClient::PaymentHooksApi)
    end
  end

  # unit tests for cancel_payment_hook
  # Cancel payment hook
  # @param id id
  # @param [Hash] opts the optional parameters
  # @return [ShowPaymentHook]
  describe 'cancel_payment_hook test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_payment_hook
  # Create payment hook
  # @param [Hash] opts the optional parameters
  # @option opts [PaymentHookCreateRequest] :payment_hook_create_request 
  # @return [ShowPaymentHook]
  describe 'create_payment_hook test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
