=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BancardPixServiceClient::PaymentHookCreateRequestPaymentHook
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BancardPixServiceClient::PaymentHookCreateRequestPaymentHook do
  let(:instance) { BancardPixServiceClient::PaymentHookCreateRequestPaymentHook.new }

  describe 'test an instance of PaymentHookCreateRequestPaymentHook' do
    it 'should create an instance of PaymentHookCreateRequestPaymentHook' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(BancardPixServiceClient::PaymentHookCreateRequestPaymentHook)
    end
  end

  describe 'test attribute "usd_amount_cents"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "buyer_cpf"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "buyer_email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "buyer_cellphone"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cashier_user_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "commerce_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "commerce_branch_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
