=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BancardPixServiceClient::ShowApplication
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BancardPixServiceClient::ShowApplication do
  let(:instance) { BancardPixServiceClient::ShowApplication.new }

  describe 'test an instance of ShowApplication' do
    it 'should create an instance of ShowApplication' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(BancardPixServiceClient::ShowApplication)
    end
  end

  describe 'test attribute "application"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
