=begin
#API V1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'date'
require 'time'

module BancardPixServiceClient
  class PaymentHook
    attr_accessor :id

    attr_accessor :usd_amount_cents

    attr_accessor :hook_alias

    attr_accessor :cashier_user_id

    attr_accessor :buyer_cpf

    attr_accessor :buyer_email

    attr_accessor :buyer_cellphone

    attr_accessor :commerce_id

    attr_accessor :commerce_branch_id

    attr_accessor :pix_copy_past

    attr_accessor :sale_id

    attr_accessor :price_national_currency

    attr_accessor :currency

    attr_accessor :vet_tax

    attr_accessor :qr_code_expiration

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :qr_base64

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'usd_amount_cents' => :'usd_amount_cents',
        :'hook_alias' => :'hook_alias',
        :'cashier_user_id' => :'cashier_user_id',
        :'buyer_cpf' => :'buyer_cpf',
        :'buyer_email' => :'buyer_email',
        :'buyer_cellphone' => :'buyer_cellphone',
        :'commerce_id' => :'commerce_id',
        :'commerce_branch_id' => :'commerce_branch_id',
        :'pix_copy_past' => :'pix_copy_past',
        :'sale_id' => :'sale_id',
        :'price_national_currency' => :'price_national_currency',
        :'currency' => :'currency',
        :'vet_tax' => :'vet_tax',
        :'qr_code_expiration' => :'qr_code_expiration',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'qr_base64' => :'qr_base64'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'usd_amount_cents' => :'Integer',
        :'hook_alias' => :'String',
        :'cashier_user_id' => :'Integer',
        :'buyer_cpf' => :'String',
        :'buyer_email' => :'String',
        :'buyer_cellphone' => :'String',
        :'commerce_id' => :'Integer',
        :'commerce_branch_id' => :'Integer',
        :'pix_copy_past' => :'String',
        :'sale_id' => :'Integer',
        :'price_national_currency' => :'String',
        :'currency' => :'String',
        :'vet_tax' => :'String',
        :'qr_code_expiration' => :'String',
        :'created_at' => :'String',
        :'updated_at' => :'String',
        :'qr_base64' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'qr_base64'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `BancardPixServiceClient::PaymentHook` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `BancardPixServiceClient::PaymentHook`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'usd_amount_cents')
        self.usd_amount_cents = attributes[:'usd_amount_cents']
      else
        self.usd_amount_cents = nil
      end

      if attributes.key?(:'hook_alias')
        self.hook_alias = attributes[:'hook_alias']
      else
        self.hook_alias = nil
      end

      if attributes.key?(:'cashier_user_id')
        self.cashier_user_id = attributes[:'cashier_user_id']
      else
        self.cashier_user_id = nil
      end

      if attributes.key?(:'buyer_cpf')
        self.buyer_cpf = attributes[:'buyer_cpf']
      else
        self.buyer_cpf = nil
      end

      if attributes.key?(:'buyer_email')
        self.buyer_email = attributes[:'buyer_email']
      else
        self.buyer_email = nil
      end

      if attributes.key?(:'buyer_cellphone')
        self.buyer_cellphone = attributes[:'buyer_cellphone']
      else
        self.buyer_cellphone = nil
      end

      if attributes.key?(:'commerce_id')
        self.commerce_id = attributes[:'commerce_id']
      else
        self.commerce_id = nil
      end

      if attributes.key?(:'commerce_branch_id')
        self.commerce_branch_id = attributes[:'commerce_branch_id']
      else
        self.commerce_branch_id = nil
      end

      if attributes.key?(:'pix_copy_past')
        self.pix_copy_past = attributes[:'pix_copy_past']
      else
        self.pix_copy_past = nil
      end

      if attributes.key?(:'sale_id')
        self.sale_id = attributes[:'sale_id']
      else
        self.sale_id = nil
      end

      if attributes.key?(:'price_national_currency')
        self.price_national_currency = attributes[:'price_national_currency']
      else
        self.price_national_currency = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'vet_tax')
        self.vet_tax = attributes[:'vet_tax']
      else
        self.vet_tax = nil
      end

      if attributes.key?(:'qr_code_expiration')
        self.qr_code_expiration = attributes[:'qr_code_expiration']
      else
        self.qr_code_expiration = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'qr_base64')
        self.qr_base64 = attributes[:'qr_base64']
      else
        self.qr_base64 = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @usd_amount_cents.nil?
        invalid_properties.push('invalid value for "usd_amount_cents", usd_amount_cents cannot be nil.')
      end

      if @hook_alias.nil?
        invalid_properties.push('invalid value for "hook_alias", hook_alias cannot be nil.')
      end

      if @cashier_user_id.nil?
        invalid_properties.push('invalid value for "cashier_user_id", cashier_user_id cannot be nil.')
      end

      if @buyer_cpf.nil?
        invalid_properties.push('invalid value for "buyer_cpf", buyer_cpf cannot be nil.')
      end

      if @buyer_email.nil?
        invalid_properties.push('invalid value for "buyer_email", buyer_email cannot be nil.')
      end

      if @buyer_cellphone.nil?
        invalid_properties.push('invalid value for "buyer_cellphone", buyer_cellphone cannot be nil.')
      end

      if @commerce_id.nil?
        invalid_properties.push('invalid value for "commerce_id", commerce_id cannot be nil.')
      end

      if @commerce_branch_id.nil?
        invalid_properties.push('invalid value for "commerce_branch_id", commerce_branch_id cannot be nil.')
      end

      if @pix_copy_past.nil?
        invalid_properties.push('invalid value for "pix_copy_past", pix_copy_past cannot be nil.')
      end

      if @sale_id.nil?
        invalid_properties.push('invalid value for "sale_id", sale_id cannot be nil.')
      end

      if @price_national_currency.nil?
        invalid_properties.push('invalid value for "price_national_currency", price_national_currency cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @vet_tax.nil?
        invalid_properties.push('invalid value for "vet_tax", vet_tax cannot be nil.')
      end

      if @qr_code_expiration.nil?
        invalid_properties.push('invalid value for "qr_code_expiration", qr_code_expiration cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @usd_amount_cents.nil?
      return false if @hook_alias.nil?
      return false if @cashier_user_id.nil?
      return false if @buyer_cpf.nil?
      return false if @buyer_email.nil?
      return false if @buyer_cellphone.nil?
      return false if @commerce_id.nil?
      return false if @commerce_branch_id.nil?
      return false if @pix_copy_past.nil?
      return false if @sale_id.nil?
      return false if @price_national_currency.nil?
      return false if @currency.nil?
      return false if @vet_tax.nil?
      return false if @qr_code_expiration.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          usd_amount_cents == o.usd_amount_cents &&
          hook_alias == o.hook_alias &&
          cashier_user_id == o.cashier_user_id &&
          buyer_cpf == o.buyer_cpf &&
          buyer_email == o.buyer_email &&
          buyer_cellphone == o.buyer_cellphone &&
          commerce_id == o.commerce_id &&
          commerce_branch_id == o.commerce_branch_id &&
          pix_copy_past == o.pix_copy_past &&
          sale_id == o.sale_id &&
          price_national_currency == o.price_national_currency &&
          currency == o.currency &&
          vet_tax == o.vet_tax &&
          qr_code_expiration == o.qr_code_expiration &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          qr_base64 == o.qr_base64
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, usd_amount_cents, hook_alias, cashier_user_id, buyer_cpf, buyer_email, buyer_cellphone, commerce_id, commerce_branch_id, pix_copy_past, sale_id, price_national_currency, currency, vet_tax, qr_code_expiration, created_at, updated_at, qr_base64].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = BancardPixServiceClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
